# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__
print(np.show_config())

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr=np.ones((3,3),dtype='int32')
arr.nbytes
arr.itemsize*arr.size

36

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector=np.zeros(10)
null_vector[4]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array_3=np.arange(10,50)
print(array_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
array_4=array_3[::-1]
print(array_4)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
array_5=np.arange(0,9) # to generate a vector with values between a given raneg
array_5.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
array_6=np.array([[1,2,0,0,4,0],[2,3,4,5,6,7]])
indices=np.where(array_6!=0) #np.where to find the indices of values in an array that satisfy a condition
print(indices) #np.where returns tupes of arrays, 1st array has the row indices and 2nd array has column indices
print(np.transpose(indices)) #to get the indices in the form of list of tuples, transpose the tuple of arrays




(array([0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64), array([0, 1, 4, 0, 1, 2, 3, 4, 5], dtype=int64))
[[0 0]
 [0 1]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
arr=np.identity(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.random((3,3,3))

array([[[0.58911008, 0.29877222, 0.90248557],
        [0.67216454, 0.74848446, 0.77334904],
        [0.96891325, 0.13881284, 0.91224005]],

       [[0.56429668, 0.15823314, 0.82632403],
        [0.94923446, 0.52210604, 0.51752292],
        [0.69920315, 0.63756733, 0.77671217]],

       [[0.93899377, 0.39955448, 0.18421663],
        [0.49752841, 0.63220182, 0.89206365],
        [0.03060458, 0.97891218, 0.36103169]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
arr=np.random.randint(10,20,size=(10,10)) #if u want random vaalues but if u wnt them to stay them the same every time you run the code, we can pass one more argument "seed"
print(arr)
print("max",arr.max())
print("min",arr.min())

[[11 10 14 16 19 16 12 11 17 11]
 [15 18 11 10 16 14 10 12 18 12]
 [18 12 11 14 18 16 11 16 11 14]
 [18 12 13 17 14 16 10 17 10 15]
 [13 18 11 16 12 10 15 10 19 16]
 [13 10 13 14 17 13 11 18 11 18]
 [16 11 14 18 10 17 14 17 13 19]
 [15 17 16 10 18 14 19 12 13 15]
 [11 18 10 18 14 11 13 19 13 13]
 [13 19 15 15 13 11 10 13 10 14]]
max 19
min 10


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
arr=np.random.randint(1,11,size=(30,))
print(arr)
print(arr.mean())

[ 8  5  4  3  5  1  4  9  9  5  8 10  3  9  2  4  5  2  9 10  3 10  5 10
  5  3  6 10  5 10]
6.066666666666666


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr=np.ones((3,4))
arr[1:-1,1:-1]=0
print(arr)



[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
arr=np.random.randint(2,10,size=(1,3))
if arr.ndim==1:
    arr=arr[np.newaxis,:]
    zeros=np.pad(arr,pad_width=1,mode='constant',constant_values=0)
else:
    zeros=np.pad(arr,pad_width=1,mode='constant',constant_values=0)


zeros

array([[0, 0, 0, 0, 0],
       [0, 6, 6, 3, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
arr=np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
zeros=np.zeros((5,5))
arr=np.arange(1,5)
zeros[arr,arr-1]=arr
print(zeros)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
blacks=np.zeros((8,8))
blacks[::2,1::2]=1
blacks[1::2,::2]=1
blacks

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
arr=np.zeros((6,7,8))
np.unravel_index(99,(6,7,8)) #to returns the index of a particulr element in a given array
#(1,5,3)

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:


arr=np.tile([[0,1],[1,0]],(4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [22]:
arr=np.arange(1,(5*3)+1).reshape(5,3)
arr2=np.arange(1,(3*2)+1).reshape(3,2)
arr3=np.matmul(arr,arr2)
arr3.shape

(5, 2)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [23]:
np.random.seed(45)
arr=np.random.randint(1,10,size=(10,))
print(arr)
arr[(arr<8) & (arr>3)]=-arr[(arr<8) & (arr>3)]
print(arr)


[4 1 6 4 5 9 2 6 7 9]
[-4  1 -6 -4 -5  9  2 -6 -7  9]


#### 26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


In [24]:
print(sum(range(5),-1)) 
#from numpy import *#when we import * from numpy, all the functions and methods in numpy module will replace buil-in python functions. so, the sum function works differently after importing *
print(sum(range(5),-1)) # here -1 is interpreted as last dimension of the array. since its a vector all the elements are summed up.
#previously -1 was considered as a second operand for the function

9
9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
z=np.arange(0,10)
print(z)
#z**z #gives us sqaure of each no in matrix
2 << z >>2
#z <- z
#1j*z
#z/1/1
#z<z>z

[0 1 2 3 4 5 6 7 8 9]


array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [37]:
a= np.random.random_sample((5,))
np.ceil(a)


array([1., 1., 1., 1., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [38]:
arr=np.arange(0,10)
arr2=np.arange(5,10)
np.intersect1d(arr,arr2)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [66]:
np.datetime64('today','M')


numpy.datetime64('2026-07')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

ValueError: Error parsing datetime string "01-07-2016" at position 8

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [93]:
np.tile(np.arange(5),5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [89]:
a=np.random.random_sample((10,))
np.sort(a)

array([0.02835481, 0.21235762, 0.38023919, 0.46537001, 0.54497486,
       0.71881652, 0.72090305, 0.7651125 , 0.83483757, 0.91979138])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [82]:
a=np.arange(10,0,-1)
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
``

TypeError: object.__reduce__() takes no arguments (1 given)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [103]:
a=np.array([1,2,4])
b=np.array([1,2,3])
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
a=np.arange(11)




(array([0], dtype=int64),)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)