# why numpy arrays over lists?
they are faster than lists. why?
only the numbers or items inside np are stored as int32 or whichever int type we specify but with the lists, things like reference count, object type and size etc are stored which take more memory, hence slower. and also while iterating through lists, computer needs to typecheck each element, so its slower.
one more reason is numpy array uses contiguous memory and all the elements will be next to each other in the computer memory unlike lists where elements are scattered around and they use pointers to access the ekements.

## How are lists and Numpy different
we can multiply two np arrays but cannot multiply two lists and can perform various mathematical operations on np arrays which is one of its applications.


In [3]:
import numpy as np

#The basics


In [4]:
a= np.array(['a','b','c'])  #initializing 1D array
a

array(['a', 'b', 'c'], dtype='<U1')

In [5]:
b = np.array([[1,2,3],[4,5,6]]) #2D ARRAY. list within a list.
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
c = np.array([[[1,2,4],[4,5,6]],[[7,8,9],[10,11,12]]]) #complexity increases as the dimensions increase
print(c)

[[[ 1  2  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
c.ndim #to get dimensions

3

In [8]:
c.shape # to gives us number of elements or blocks in each dimension

(2, 2, 3)

In [9]:
a.shape

(3,)

In [10]:
a.dtype  #dtype gives us the type of elements in an array

dtype('<U1')

In [11]:
c.dtype

dtype('int64')

In [12]:
d=np.array([1,2,3],dtype=np.int16) #if u know that an array not gonna have big values, u can specify the dtype to save storage

In [13]:
d.dtype

dtype('int16')

In [14]:
a.size # size gives us total elements in an array

3

In [15]:
c.size

12

In [16]:
b.itemsize #itemsize gives us size of each element in bytes

8

In [17]:
a.nbytes #nbytes gives us total size of an array in bytes which is basically number of elements multiplied by bytes taken by each element

12

In [18]:
b.nbytes

48

# Accesing or changing specific elements, rows, columns etc

In [19]:
a=np.array([[1,2,3,4,5,6,7,8],[11,12,13,14,15,16,17,18]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [11 12 13 14 15 16 17 18]]


In [20]:
# basicially, to access an element from a particular row and column we use the format a[row,column]
print(a[1,2]) # gives us element at 2nd row 3rd column

13


In [21]:
#if we want to get range of elements starting from one point and ending at another, we can use slicing
#same format, with one change a[start:end,start:end]
a[0,2:5] # gives us element from 1st row in the columns starting from 3rd to 5th colummn
a[:,::2] #we can choose elements between two points with a step as well using a[start:end:step,start:end:step] this format

array([[ 1,  3,  5,  7],
       [11, 13, 15, 17]])

In [22]:
a[1][3:6]

array([14, 15, 16])

In [23]:
#lets access elements from 3d array
c = np.array([[[1,2,4],[4,5,6]],[[7,8,9],[10,11,12]]])

In [24]:
c[1][:][:] # elements from both the big blocks and also both the subblocks and also both the rows in the sublocks with step 2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
c[1,:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [26]:
#changing specific element
c[0,0,:]=[16,17,18]
c

array([[[16, 17, 18],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Initializing different types of arrays


In [27]:
# all zero matrix
e = np.zeros((5,)) #pass shape as the argument

e

array([0., 0., 0., 0., 0.])

In [28]:
# all 1s matrix
f= np.ones((3,3,3), dtype=np.int32)

In [29]:
f

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [30]:
 #use np.full to generate array with the numbers u want, use np.full_like to use the shape of already defined array to generate a new array
a = np.full((3,4,5),69,dtype=np.float32)
a=np.full_like(c,5)
a

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [31]:
#to generate an array with random numbers
b=np.random.rand(4,2,1)

In [32]:
b

array([[[0.70098321],
        [0.9882856 ]],

       [[0.01554809],
        [0.36621324]],

       [[0.86658257],
        [0.45921036]],

       [[0.15351317],
        [0.41163957]]])

In [33]:
b = np.random.random_sample(a.shape) #this is same as the random.rand but the only difference is that u can pass a different arrays shape as an argument which u cannot do with the rand function

In [34]:
b

array([[[0.77730382, 0.11473097, 0.45887816],
        [0.43615709, 0.97181381, 0.36127538]],

       [[0.19069272, 0.79152977, 0.87984404],
        [0.94507767, 0.97183483, 0.1647522 ]]])

In [62]:
 #lets say i dont want the random numbers to be decimals but want them to be integer, then use
c=np.random.randint(-1,2, size=(3,3,3))  # this takes a 3 arguments. start and end. the random numbers will be between these two numbers.
 # and also instead of shape it takes size which is one nd the same here. wierd thing to remember
#start should be less than end number

In [63]:
c

array([[[ 0, -1,  1],
        [-1, -1,  0],
        [ 0,  0,  0]],

       [[-1,  1,  1],
        [ 0,  0, -1],
        [ 1,  0,  0]],

       [[ 0,  1, -1],
        [ 1,  0,  0],
        [ 1, -1,  1]]])

In [55]:
#to create identity matrix
id=np.identity(3) #takes just one argument as identity matrix is a square matrix with 1s on diagonal

In [56]:
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
#if i want to repeat a certain matrix horizontally or vertically, i can use
rep=np.repeat(c,2,axis=0) #this takes 3 arguments, the matrix that u wanna repeat, how many times u want to repeat and the axis
# to determine whether u wanna repeat the matrix horizontally or vertically. if we dont specify, itll result in horizontal matrix by defaut

In [70]:

rep

array([[[ 0, -1,  1],
        [-1, -1,  0],
        [ 0,  0,  0]],

       [[ 0, -1,  1],
        [-1, -1,  0],
        [ 0,  0,  0]],

       [[-1,  1,  1],
        [ 0,  0, -1],
        [ 1,  0,  0]],

       [[-1,  1,  1],
        [ 0,  0, -1],
        [ 1,  0,  0]],

       [[ 0,  1, -1],
        [ 1,  0,  0],
        [ 1, -1,  1]],

       [[ 0,  1, -1],
        [ 1,  0,  0],
        [ 1, -1,  1]]])

In [71]:
rep.shape#it basically repeats each row or column depending on the axis based on the no of repetitions

(6, 3, 3)

In [ ]:
a=np.random.randint(3,6,size=(3,3,3))

In [ ]:
a

array([[[5, 4, 4],
        [4, 4, 4],
        [5, 5, 5]],

       [[3, 5, 3],
        [4, 5, 4],
        [5, 4, 5]],

       [[4, 4, 4],
        [3, 5, 3],
        [4, 4, 4]]])

In [ ]:
a[:2,0:2,0:2]

array([[[5, 4],
        [4, 4]],

       [[3, 5],
        [4, 5]]])

In [ ]:
#be careful when copying array
a=np.array([1,2,3])
b=a#if we copy arrays like this and then change something the in 2nd array, it will result in the change in first array as well
b[1]=8
print(a)
print(b)

[1 8 3]
[1 8 3]


In [73]:
#so use copy function
a=np.array([1,2,3])
b=a.copy()
b[1]=8
print(a)
print(b)

[1 2 3]
[1 8 3]


#mathematics


In [74]:
#to do maths operations element by element, just do
a+b # but if u wanna use the resulting array, u need to store it in a variable


array([ 2, 10,  6])

In [75]:
a+2

array([3, 4, 5])

In [77]:
#u can do simple mathematical functions like multpliaction, division sub
a**2

array([1, 4, 9])

#linear algebra

In [87]:
#to do matrix multiplication, u cant just use "*" to multiply two matrices, instead we need to use, np.matmul
a=np.full((2,2),1)
print(a)
b=np.full((2,2),2)
print(a*b)


[[1 1]
 [1 1]]
[[2 2]
 [2 2]]


In [89]:
#we can find min,max along column or rows
k=np.random.randint(3,6,size=(3,3,3))
k

array([[[5, 3, 5],
        [5, 4, 4],
        [3, 3, 4]],

       [[3, 4, 5],
        [3, 5, 5],
        [5, 4, 5]],

       [[5, 4, 4],
        [4, 4, 5],
        [3, 4, 4]]])

In [91]:
np.min(k,axis=0)

array([[3, 3, 4],
       [3, 4, 5],
       [3, 4, 4]])

In [92]:
np.sum(k,axis=0)

array([[13, 11, 14],
       [12, 13, 14],
       [11, 11, 13]])

#for more mathematical functions,

https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa3hsZVFQZHgtRG9EZExzSzZjYlN4RWtjVm1YZ3xBQ3Jtc0tsMTdQdXdab2VDa0Y3cDJ0TnVaUTh5dDF6WElfdENhbWVET2lPY2JmMWdoQ1N3OFB5Z2hhUUJfNGlJSUQyT01ZV2RkODZNNGlUSWRDMXRvUzRrNVZCUkd2VUlJWEw1VUxlX01PVnY1NEpsTTg4QVJJQQ&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.linalg.html&v=QUT1VHiLmmI use this link

#Reorganizing Arrays

In [ ]:
#if we want to reshape an array we can use np.reshape(), but the resulting array should have same no of elements
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b=np.reshape(a,(2,3,1))

In [ ]:
c=np.zeros((2,3))

In [ ]:
#we can stack matrices as well using vstack and hstack
np.hstack((a,c))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [ ]:
np.vstack((a,c))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Miscellaneous

#load data from a file


In [ ]:
data=np.genfromtxt('/content/drive/MyDrive/Colab Notebooks/Job ready /data.txt',delimiter=',') #takes 2 arguments, filepath and delimiter which how the values aare seperated in our text file
data= data.astype('int32') # by default , it converts the value into float, so we need to convert them to int using astype
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

# boolean masking and advanced indexing

In [ ]:
data>50 # gives us true or false for each position in the array based on the condition

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
#if u wanna get the actual values in the array that satisifes the condition, use this
data[data>60]

array([196,  75, 766,  75, 999,  78,  76,  88], dtype=int32)

In [ ]:
#we can index or access elements using list in numpy, not very efficient for 2d or arrays with more than 1 d

a=np.ones((5,5),dtype='int32')
print(a)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
a[[0,2,4],2:]

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
#if i wanna know if any value along the columns satisfy a condition, use this
np.any(data>50,axis=0)
#to check values along the row
np.any(data>50,axis=1)

array([ True,  True,  True])

In [ ]:
#we can check if all the vlaues satisy condition using this
np.all(data>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [93]:
test=np.random.randint(2,50,(3,3))

In [105]:
test

array([[39, 42, 32],
       [21, 19, 36],
       [12,  4, 37]])

In [108]:
np.all(test>5,axis=0)

array([ True, False,  True])